host: "localhost:3000"
storage: :file
google_client_id: <%= Rails.application.credentials.google[:client_id] %>
google_client_secret: <%= Rails.application.credentials.google[:client_secret] %>
google_api_key: <%= Rails.application.credentials.google[:api_key] %>